### ISSUE TITLE
Figure out how to adjust release script

### ISSUE THREAD

**Issue by lydia-duncan** [chapel-lang/sphinxcontrib-chapeldomain#49]
util/release.bash includes the lines:
```
echo "Pushing tags to chapel-lang remote..."
git push https://github.com/chapel-lang/sphinxcontrib-chapeldomain --tags
```

This triggered an email from Github to me about using my password to push to github because the `https:` form will always using passwords and that support will be deprecated by August 2021.  However, we can't guarantee the name used by the particular remote that corresponds to the chapel-lang repo - it could be `origin`, it could be `chapel`, it could be `chapel-lang`, etc.

There's probably a way to compute it by searching the remotes defined for one with the right address.  I'm also open to other ideas.

**Comment by ronawho** [comment]
I'm not sure I follow this. I think the simple fix is to just switch from https to ssh and allow users to override the url. 

The part I'm not sure I follow is about the name of the remote repo. Here it's not using `origin`/`chapel-lang` or any git remote alias, but instead pushing tags directly to the url. i.e. it's not `git push origin --tags`, but instead `git push <full url> --tags`. Maybe you want to be able to create a release on your fork and not on chapel-lang though?

Probably the cleaner way to do this though is to create a new github action to release, instead of having a manual script.

**Comment by lydia-duncan** [comment]
> The part I'm not sure I follow is about the name of the remote repo. Here it's not using `origin`/`chapel-lang` or any git remote alias, but instead pushing tags directly to the url. i.e. it's not `git push origin --tags`, but instead `git push <full url> --tags`. Maybe you want to be able to create a release on your fork and not on chapel-lang though?

Nah, I still want it to work for the chapel-lang repo.  The mod that I have locally amounts to `git push chapel-lang --tags`, which has worked the last couple of times I tried it.  I'll try using ssh the next time I need to run it, that's a good idea.

> Probably the cleaner way to do this though is to create a new github action to release, instead of having a manual script.

Yeah, or getting a Jenkins job for it or something.  I think the main problem with that is that it needs a PyPI account tied to it

**Comment by lydia-duncan** [comment]
Looks like if you don't provide an explicit username for the ssh version, git will attempt to use the one on your machine (which doesn't match my personal Github username)

**Comment by ronawho** [comment]
>> Probably the cleaner way to do this though is to create a new github action to release, instead of having a manual script.

> Yeah, or getting a Jenkins job for it or something. I think the main problem with that is that it needs a PyPI account tied to it

Doing this through github actions is probably easiest since there are actions designed to help with this: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

The action I linked to will automatically upload a package to pypi on "release", but we don't do official releases, just tags, so we'd probably need to combine this with some other actions to tag and then have it be manually triggered instead of automatically running on release.

And it uses github secrets to public to PyPI (create a token on PyPi, add that as a repo secret, and then only repo members with the right permissions are able to kick off the job that will tag/publish to pypi)

**Comment by ronawho** [comment]
Github action job to automatically release was added in https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/57 and the old release script was removed in https://github.com/chapel-lang/sphinxcontrib-chapeldomain/pull/59.
